version: "3.9"
# 컨테이너이름
services:
    back:
        build: ./back
        ports:
            - "3001:3001"
        volumes:
            - ./back:/tamastudy/back
            - /tamastudy/back/node_modules
        networks:
            - backend
    front:
        build:
            context: ./front
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        stdin_open: true
        volumes:
            - ./front:/tamastudy/front
            - /tamastudy/front/node_modules
        depends_on:
            - back
        networks:
            - frontend
    mysql:
        build:
            context: ./back/database/todolist.sql
        image: mysql:5.7
        networks:
            - backend
            - frontend
# network 숙제
# 디비mysql+ 투두리스트
# 쿠버네티스 -> 컨테이너들을 대비, 복사
